# XNXGAMES_Board
server:
  port: 8082

# DB
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/XNXGAMES_board?serverTimezone=UTC&characterEncoding=UTF-8
    username: XNXGAMES_BOARD
    password: 5460
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

# Default
  application:
    name: board

# RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Discovery
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
      
# Log
logging:
  config: classpath:logback-spring.xml
  
# Resilience4j
resilience4j:  circuitbreaker:    configs:      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
    instances:
      default:        baseConfig: default  retry:    configs:      default:
        wait-duration: 100
    instances:      default:
        base-config: default
  bulkhead:    configs:      default:
        max-concurrent-calls: 100
    instances:      default:
        base-config: default
  thread-pool-bulkhead:    configs:      default:
        max-thread-pool-size: 4
        core-thread-pool-size: 2
        queue-capacity: 2
    instances:      default:
        base-config: default
  ratelimiter:    configs:      default:
        register-health-indicator: false
        limit-for-period: 10
        limit-refresh-period: 1s
        timeout-duration: 0
        event-consumer-buffer-size: 100
    instances:      default:
        base-config: default
  timelimiter:    configs:      default:
        cancel-running-future: false
        timeout-duration: 2s
    instances:      default:
        base-config: default